### ISSUE TITLE
node-mcp23017 module doesn't work

### ISSUE THREAD

**Issue by scramble45** [igorklopov/enclose#137]
**Using:** enclose@2.2.0 full version / Node v6.4.0

[https://www.npmjs.com/package/node-mcp23017](https://www.npmjs.com/package/node-mcp23017)

````
$ enclose mcp23017.js

/node_code/node_modules/i2c/main.js
  error  Cannot find module './lib/i2c' from '/node_code/node_modules/i2c'
````

Any suggestions?

**Comment by igorklopov** [comment]
i2c is written in CoffeeScript and published in CoffeeScript as well. However it is not good because:
* Every time a project is launched it wastes time on transpiling Coffee sources to JavaScript (in runtime)
* EncloseJS can not parse and traverse dependencies in CoffeeScript code.
Please vote for PR: https://github.com/kelly/node-i2c/pull/81

**Comment by scramble45** [comment]
Thanks for the feedback Igor, I will see about porting or using another library.

**Comment by scramble45** [comment]
So I converted the node-i2c library to native javascript from coffee script. Seems to be working: 
[https://github.com/scramble45/i2cjs](https://github.com/scramble45/i2cjs)

I have modified my node-mcp23017 fork to point to this: [https://github.com/scramble45/i2cjs](https://github.com/scramble45/i2cjs), Now I am seeing this when I try to enclose:

````
 $ enclose mcp23017.js

/node_code/node_modules/node-mcp23017/node_modules/i2c/build/Release/i2c.node
  warning  Cannot include native addon into executable.
  The addon file must be distributed with executable.

````

Any suggestions, I am fine with moving the i2c.node to the running folder it doesn't need to be enclosed I just need to code enclosed.

**Comment by scramble45** [comment]
resolved
