### ISSUE TITLE
Nodegit support

### ISSUE THREAD

**Issue by Globegitter** [igorklopov/enclose#15]
When I am trying to compile my app with nodegit I get the following warnings/errors:

``` js
projects/blame-history/node_modules/nodegit/lib/nodegit.js
  warning  Cannot resolve 'require("./" + name)'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option

projects/blame-history/node_modules/nodegit/node_modules/promisify-node/index.js
  warning  Cannot resolve 'require(name)'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option

projects/blame-history/node_modules/nodegit/build/Release/nodegit.node
  warning  Cannot include native addon into executable
  The addon package must be distributed with executable
```

So I guess to get over the first two warnings I would ideally find out what the `name` can resolve to and then list it in the `scripts` option right? Is there any documentation on the scripts option? I couldn't find anything.

And not quite sure about the last one. I have seen the section on native addons, but don't quite understand. When I run the app I get the following error:

```
Error: dlopen(/Users/markus/Projects/blame-history/node_modules/nodegit/build/Release/nodegit.node, 1): no suitable image found.  Did find:
    /Users/markus/Projects/blame-history/node_modules/nodegit/build/Release/nodegit.node: mach-o, but wrong architecture
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at G (<anonymous>)
    at N (<anonymous>)
    at c (<anonymous>)
    at Object.Math.Enclose.+/+t+h+e+b+o+x+/+U+s+e+r+s+/+m+a+r+k+u+s+/+P+r+o+j+e+c+t+s+/+b+l+a+m+e+-+h+i+s+t+o+r+y+/+n+o+d+e+_+m+o+d+u+l+e+s+/+n+o+d+e+g+i+t+/+l+i+b+/+n+o+d+e+g+i+t+.+j+s (<anonymous>)
    at u (<anonymous>)
```

Does that mean it has been built for the wrong node/iojs?

**Comment by igorklopov** [comment]
You are right. All .js files from `nodegit/lib/nodegit.js` must be explicitly specified for enclose. I just did that - i added new item `nodegit.js` into the dictionary: https://github.com/igorklopov/enclose/blob/master/dictionary/nodegit.js so that enclose will work correctly for any project using nodegit. To use new dictionary entry upgrade to enclose@0.2.10.

Second issue (with nodegit.node). I see `mach-o, but wrong architecture` in your log. Enclose makes x86 executable by default. To make x64 you should pass `-x` option to command line. Probably your node is x64, node-gyp built nodegit as x64 library, but enclose made x86 executable because `-x` was not passed. Please use `file ./youapp` also `file ./nodegit.node` and also try adding `-x`.

**Comment by Globegitter** [comment]
@igorklopov Thank you for the quick response. It still shows the warning but more importantly all working now! Really appreciated :)
