### ISSUE TITLE
sqlite3 error

### ISSUE THREAD

**Issue by BilalBoulifa** [igorklopov/enclose#40]
I'm getting this error when trying to run my generated exe

undefined:0

Error: Cannot find module 'D:\Users\bb14193\Downloads\WorkFolder\node_modul
es\sqlite3\lib\binding\node-v14-win32-ia32\node_sqlite3.node'
  at Error (native)
  at O (<anonymous>:null:null)
  at c (<anonymous>:null:null)
  at Object.Math.Enclose.+d+:++t+h+e+b+o+x++U+s+e+r+s++b+b+1+4+1+9+3++D
+o+w+n+l+o+a+d+s++W+o+r+k+F+o+l+d+e+r++n+o+d+e+_+m+o+d+u+l+e+s++s+q+l+i+
t+e+3++l+i+b++s+q+l+i+t+e+3+.+j+s.dev (<anonymous>:null:null)
  at u (<anonymous>:null:null)
  at O (<anonymous>:null:null)
  at c (<anonymous>:null:null)
  at Object.Math.Enclose.+d+:++t+h+e+b+o+x++U+s+e+r+s++b+b+1+4+1+9+3++D
+o+w+n+l+o+a+d+s++W+o+r+k+F+o+l+d+e+r++a+p+p+.+j+s.dev (<anonymous>:null:
null)
  at u (<anonymous>:null:null)
  at <anonymous>:null:null
  at Math.Enclose (<anonymous>:null:null)
  at _third_party_main.js:1:76
  at NativeModule.compile (node.js:805:5)
  at Function.NativeModule.require (node.js:774:18)
  at node.js:75:22
  at process._tickCallback (node.js:355:11)

**Comment by igorklopov** [comment]
What is your node version? Maybe iojs? Sqlite3 is covered by internal tests and should run well.

**Comment by BilalBoulifa** [comment]
0.12.0

**Comment by igorklopov** [comment]
I checked sqlite3 again - it is ok. Please ensure that file `D:\Users\bb14193\Downloads\WorkFolder\node_modul
es\sqlite3\lib\binding\node-v14-win32-ia32\node_sqlite3.node` exists. Also post your `process.arch` and enclosejs compilation command line.
ALSO: Please remember that EncloseJS can not attach native addon to generated executable. You must ship module `sqlite3` because it has native addons. You can ship only file `node_sqlite3.node`.
